name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: dart-test-2022/basicfunctionHomework_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - name: Set up Dart environment
        uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test --file-reporter json:tests.json
